# -*- coding: utf-8 -*-
"""Practice Sheet 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alF0RAnV1nnSrumQsEIvS6REGyDC2cBV
"""

#2
##>>> 5**9
##1953125
##>>> 3//2
##1
##>>> 7//3
##2
##>>> 6==6
##True
##>>> a=20
##>>> a+=30
##>>> a%=3
##>>> print(a)
##2
##>>> True*False
##0
##>>> True&False
##False
##>>> True and False
##False
##>>> ((6>3) and (7<4) or (18==3)) and (9>3)
##False
##>>> True is False
##False
##>>> False in 'False'
##Traceback (most recent call last):
##  File "<pyshell#13>", line 1, in <module>
##    False in 'False'
##TypeError: 'in <string>' requires string as left operand, not bool
##>>> ((True==False) or (False>True)) and (False <=True)
##False

#3 
s1 = "Nice to have it"
s2 = "here"
s1 + " " + s2


#4
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

#5
s1 = "Nice to have it"
s2 = "here"
a = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a.append(s2)
a.insert(0,s1)
print(a)

#6
color_list_1 = set(["White", "Black", "Red"])
color_list_2 = set(["Red", "Green"])
print("Original set elements:")
print(color_list_1)
print(color_list_2)
print("\nDifferenct of color_list_1 and color_list_2:")
print(color_list_1.difference(color_list_2))

#7
string=input("enter a string")
string.lower()
list=list(string)
set=set(list)
set.remove(' ')
t=len(set)
if t==26:
    print("string is pangram")
else:
    print("string is not pangram")

#8
eval('{0}+{0}{0}+{0}{0}{0}'.format(input('Enter the number')))

#9 
words = input("Input words: ")
word_list = words.split(",")
word_list.sort()
print((', ').join(word_list))

#10
d={'student':['Rahul','Kishore','Vidhya','Raakhi'],'marks':[57,87,67,79]}
m=(d['marks'])
print("Max marks are",(max(d['marks'])))
s=(d['student'])
print("Student who get max marks is",s[m.index(max(d['marks']))])
